%{
Write a MATLAB script for the given problem:

The electricity generated by wind turbines annually in
kilowatt-hours per year is given in the turbine_data.dat file. 
The amount of electricity is determined by, among other factors,
the diameter of the turbines blade (in feet) and
the wind velocity in mph. The file stores on each line
the blade diameter, wind velocity, and the approximate
electricity generated for the year. For example,

5 5 406
5 10 3250
5 15 10970
5 20 26000
10 5 1625
10 10 13000
10 15 43875
10 20 104005

Access the file turbine_data.dat in this format and determine
how to display this data graphically to show the relationship 
between the blade diameter, wind velocity and the electricity generated.
%}

D = load('turbine_data.dat');

% the 2nd column of data contains speed of the wind turbine so store it in a variable named speed
speed=D(:,2);

% the first 4 data points are for 5 feet blade diameter so extract and store them in variable speed_5
speed_5=speed(1:4);

% from the 5th data point to the end of vector contains data for 10 feet blade diameter so extract and store them in variable speed_10.
speed_10=speed(5:end);

% the 3rd column of data contains generated electricity of the wind turbine so store it in a variable named kwh
kwh=D(:,3);

% the first 4 data points are for 5 feet blade diameter so extract and store them in variable kwh_5
kwh_5=kwh(1:4);

% from the 5th data point to the end of vector contains data for 10 feet blade diameter so extract and store them in variable kwh_10.
kwh_10=kwh(5:end);

% Plot the speed _5 on x-axis and corresponding kwh_5 on y-axis
plot(speed_5,kwh_5,'LineWidth',2)

% hold on means we want to plot another curve in the same graph so wait
hold on

% Plot the speed _10 on x-axis and corresponding kwh_10 on y-axis
plot(speed_10,kwh_10,'LineWidth',2)

% legend command provides visual aid to distinguish between the two curves
legend('5 feet blade','10 feet blade')

% set the title of the graph, x-axis and y-axis labels
title('Generated Electricty Vs Wind speed')

xlabel('Wind speed (mph)')

ylabel('Generated Electricity (kWh)')